databaseType = "PostgreSql"
id = "e3f145f2-bc4d-413f-a9e9-6bf248d65bc5"
name = "DB-project_test"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true
baselineVersion = "000"
baselineOnMigrate = true

[flywayDesktop]
enableMigrations = true
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.JSK-119]
url = "jdbc:postgresql://localhost:5432/JSK-119"
schemas = [
  "public",
  "utility",
  "tests",
  "test_gis",
  "temp",
  "tarif",
  "support",
  "special",
  "sms",
  "service",
  "security",
  "report",
  "recalculation",
  "portal",
  "person",
  "period",
  "payment",
  "partner",
  "parametr",
  "organization",
  "normativ",
  "law",
  "input",
  "import",
  "house",
  "group",
  "gis",
  "flat",
  "fine",
  "export",
  "exchange",
  "eco",
  "domyland",
  "documents",
  "dbo",
  "counter",
  "contragent",
  "connection",
  "call",
  "calculation",
  "benefit",
  "bank",
  "api",
  "adress",
  "account",
  "1c"
]
displayName = "JSK-119"
