-- Script generated by Redgate Compare v1.53.0.3647


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping recalculation.result.update_values_recalculation...';END$$;
DROP TRIGGER update_values_recalculation ON recalculation.result;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping recalculation.result.insert_values_recalculation...';END$$;
DROP TRIGGER insert_values_recalculation ON recalculation.result;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Dropping public...';END$$;
COMMENT ON SCHEMA public IS NULL;

