-- Script generated by Redgate Compare v1.53.0.3647


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating recalculation.result.update_values_recalculation...';END$$;
CREATE TRIGGER update_values_recalculation
AFTER UPDATE
ON recalculation.result
REFERENCING OLD TABLE AS deleted
NEW TABLE AS inserted
FOR EACH ROW
EXECUTE PROCEDURE recalculation.insert_values();


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating recalculation.result.insert_values_recalculation...';END$$;
CREATE TRIGGER insert_values_recalculation
AFTER INSERT
ON recalculation.result
REFERENCING NEW TABLE AS inserted
FOR EACH ROW
EXECUTE PROCEDURE recalculation.insert_values();


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public...';END$$;
COMMENT ON SCHEMA public IS 'standard public schema';

